spring:
  application:
    name : springbootZuul
  zipkin:
    base-url : http://10.1.192.36:9411
    enabled : true
    locator:
      discovery:
        enabled: true
    sender:
      type: WEB
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1
server:
  port : 6005

eureka:
  client:
    service-url:
      defaultZone : http://localhost:5000/eureka/

zuul:
  routes:
    sbService :
      path : /sbService/**
      serviceId : springbootService
